### ISSUE TITLE
No equivalent method to send messages for "sendToAllNearExcept"

### ISSUE THREAD

**Issue by darkevilmac** [elytra/Concrete#3]
There's no method for sending messages that behaves like "sendToAllNearExcept" in net.minecraft.server.management.PlayerList

**Comment by darkevilmac** [comment]
Alternatively just add a method to send to players matching a predicate. sendToAllMatching or something

**Comment by unascribed** [comment]
*testing IA*

**Comment by exaskye** [comment]
fine i'll do it
