### ISSUE TITLE
Use Generics in Marshallable

### ISSUE THREAD

**Issue by darkevilmac** [elytra/Concrete#5]
The title.

This would allow manipulation of the return value for readFromNetwork, so you can set a flag for certain cases to return static instances of variables.

**Comment by exaskye** [comment]
Uh, traits?

**Comment by exaskye** [comment]
...What would generics help with in Marshallable, exactly?

Marshallable means "this object can be marshalled". Any use cases I can think of for Marshallable generics are covered by Marshaller.
